# Generated by Django 5.2 on 2025-04-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('repeat', models.BooleanField(default=False)),
                ('number_of_weeks', models.IntegerField(default=0)),
                ('days', models.CharField(max_length=250)),
            ],
        ),
    ]
