# Generated by Django 5.2 on 2025-04-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurance',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='occurance',
            old_name='start_time',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='scheduledevent',
            old_name='number_of_weeks',
            new_name='repeat_number_of_weeks',
        ),
        migrations.RenameField(
            model_name='scheduledevent',
            old_name='start_time',
            new_name='start_datetime',
        ),
    ]
